apiVersion: apps/v1
kind: Deployment
metadata:
  name: icndb-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: icndb-app-operator
  template:
    metadata:
      labels:
        name: icndb-app-operator
    spec:
      serviceAccountName: icndb-app-operator
      containers:
        - name: icndb-app-operator
          # Replace this with the built image name
          image: nikhilvep/icndb-app-operator:version-exp
          command:
          - icndb-app-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "icndb-app-operator"
