kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: icndb-app-operator
subjects:
- kind: ServiceAccount
  name: icndb-app-operator
  namespace: funapp-operator-ns-1
roleRef:
  kind: ClusterRole
  name: icndb-app-operator
  apiGroup: rbac.authorization.k8s.io
